// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxWjmwnK6-D9fOBp9iqanH77PqSih9Hs',
    appId: '1:906355971972:web:202edb45d2de9a529c6fd1',
    messagingSenderId: '906355971972',
    projectId: 'user-login-92c12',
    authDomain: 'user-login-92c12.firebaseapp.com',
    storageBucket: 'user-login-92c12.appspot.com',
    measurementId: 'G-RQ6T673M12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHeUromUpXrREn5D5gmScTAnn680ed9DU',
    appId: '1:906355971972:android:3e2200b6d808ec8f9c6fd1',
    messagingSenderId: '906355971972',
    projectId: 'user-login-92c12',
    storageBucket: 'user-login-92c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOcxlIy1IwQuNKn22fMwzoH5hCg2kk_o',
    appId: '1:906355971972:ios:c8faa26a7e26ba499c6fd1',
    messagingSenderId: '906355971972',
    projectId: 'user-login-92c12',
    storageBucket: 'user-login-92c12.appspot.com',
    iosClientId: '906355971972-4is45fkkodploep0khh7u4rb2i7hp6at.apps.googleusercontent.com',
    iosBundleId: 'main',
  );
}
